### ISSUE TITLE
Problems with stub_command on only_if block

### ISSUE THREAD

**Issue by adamjk-dev** [sethvargo/chefspec#256]
I had a recipe with a resource that had the following only_if block:

``` ruby
only_if {File.exists?(install_file) && !File.exists?("#{install_dir}/bin/java")} #If the installer file exists, run it
```

I tried to do a stub_command, but could not get it to work. The test (checking for a run_execute) kept failing without warning me to add a stubbed command to make that true. 

Is there any syntax support for the above only_if block in a stub_command?

As a workaround, I had to change my only_if block and stub_command to the following:

``` ruby
only_if "test -e #{install_file} && test ! -e #{install_dir}/bin/java" #If the installer file exists, run it

stub_command("test -e /tmp/jrockit-jdk1.6.0_31-R28.2.3-4.1.0-linux-x64.bin && test ! -e /opt/weblogic/java/jrmc-1.6.0_31/bin/java").and_return(true)
```

**Comment by flatrocks** [comment]
Possibly related, hopefully helpful.  Using a similar only_if guard,
``` ruby
only_if { Dir.glob('my_dir/*'), 0).empty? }
```
I tried stubbing out the Dir.glob to return an empty, or non-empty array, ala:
``` ruby
allow(Dir).to receive(:glob).with('/my_dir/*', 0).and_return []
allow(Dir).to receive(:glob).with('/my_dir/*', 0).and_return ['something_here']
```
However the script ALWAYS ran.

I realized that the Dir.glob stub was getting hit twice, but only returned my specified return value the first time.  (This may simply show I am missing something about the "new" rspec mock/stub usage, but...) my solution turned out to be simple:
``` ruby
allow(Dir).to receive(:glob).with('/my_dir/*', 0).at_least(:once).and_return []
```
With the ```at_least(:once)```, the glob stub returned the expected value _each_ time, and the test ran as expected.


__The key to figuring this out was in splitting up the guard to dump some debug info__, changing this,
``` ruby
only_if { Dir.glob('/my_dir/*', 0).empty? }
```
to this:
``` ruby
only_if do
    puts Dir.glob('/my_dir/*', 0)
    puts Dir.glob('/my_dir/*', 0).empty?
    Dir.glob('/my_dir/*', 0).empty?
end
```
...to see what the heck was going on.  Mine was clearly a problem with my use of rspec, and not chefspec at all, but that was not clear until I'd solved it.  I suspect the same for this issue and #250.

**Comment by rehevkor5** [comment]
I'm having the same problem. The method in the `not_if` block is definitely not getting stubbed the way it does outside the `not_if` block. The method isn't stubbed within the block for the resource, either.

**Comment by kplimack** [comment]
@sethvargo how would I stub something like this?
```
execute 'do something with consul' do
  [...snip...]
  only_if 'pidof /opt/consul/consul'
end
```

**Comment by avinashgaonkar** [comment]
@adamjk-dev were u able to resolve the issue, were you able to use ruby methods in spec?
i am trying to use below but spec fails.
not_if { ::File.exist?('/etc/exports') }

**Comment by adamjk-dev** [comment]
I haven't checked in a few years, sorry. This was a long time ago.

**Comment by avinashgaonkar** [comment]
No issues, I have used bash based not_if, it worked.

Thanks.
Avinash
