### ISSUE TITLE
error message stating "I cannot read C:\chef\client.pem which you told me to use to sign requests"

### ISSUE THREAD

**Issue by trekr5** [sethvargo/chefspec#578]
Hello,

This is my recipe:

```ruby
require 'spec_helper'

describe 'core::local_users_linux' do 
	 let (:chef_run) { ChefSpec::SoloRunner.new.converge('core::local_users_linux') }	
	 let(:databag){Chef::EncryptedDataBagItem.load("aws-admin-passwords", "svc_goagent")}

	before do
			allow(databag).and_return({
                "id" => "svc_goagent",
                "password" => "London2014"
				})
	end
 
    context 'linux' do
	       it 'stubbed databag does not raise error with aws-admin-passwords databag and svc_goagent id' do
	       	 expect(chef_run).to_not raise_error
	       end
	end	
end
```

When the above ChefSpec test is run, I get the error "I cannot read C:\chef\client.pem which you told me to use to sign requests". Can someone please take a look and tell me what I'm doing wrong?

Essentially I'm trying to decrypt a stubbed encrypted databag and return the values specified in the test. I don't expect the test to perform an actual decryption.

**Comment by sethvargo** [comment]
If you don't want the decryption to happen, then you can't call `Chef::EncryptedDataBagItem.load`, since that is going to try and download the databag from a non-existent Chef Server.

Please see the RSpec stubbing documentation for details on how to stub this out. You may also be interested in this issue: https://github.com/sethvargo/chefspec/issues/515.
