### ISSUE TITLE
Override of map-valued Node Attribute

### ISSUE THREAD

**Issue by michaellihs** [sethvargo/chefspec#610]
Thanks a lot for your work on this great framework!

I have a problem with overriding map-valued node attributes. A full description of the problem can be found here: http://stackoverflow.com/questions/31490187/chef-node-attribute-is-not-overridden-in-chefspec

I can easily override all other node attributes (scalar valued), but with this map-valued attribute, it somehow seems not to work.

Any hint is highly appreciated.

**Comment by sethvargo** [comment]
Can you please share your complete recipe and spec files please? Are you able to narrow this down to a smaller use-case, maybe without the Jenkins cookbook? That would help me in diagnosing and fixing this issue.

**Comment by michaellihs** [comment]
Hey Seth,

thx a lot for this really quick response!!! I will try to provide you a "small example" of the problem. Also it might be a good idea (for me) to try and reproduce it in a smallest-possible setup to see wether the problem lies somewhere else!

Thx!

**Comment by sethvargo** [comment]
@michaellihs my suspicion is that this is something with the Jenkins cookbook you are using and the way it's declaring resources. I would also need to know your Chef version and ChefDK version (if applicable). If you search through some closed issues, you'll find that issue reports are solved much quicker if you create a public github repo that I can just clone and see the issue.

**Comment by michaellihs** [comment]
@sethvargo  Ok - I tried to strip it down to "the essence" and created this repository with all the relevant files to reproduce the issue:

https://github.com/michaellihs/jenkins-chefspec

If I got it  right, the recipes of the Jenkins community cookbook are not used at all, since I only test the wrapper cookbook that calls the resources from the Jenkins cookbook.

I am using rspec 3.3.2 and have the Chef Development Kit 0.4.0 installed. But I suppose, the ChefDK is not used, when I run the tests directly via rspec?

The steps to reproduce the problem are in the README of the repository.

Thanks a lot for your help!

**Comment by sethvargo** [comment]
Hi @michaellihs 

After some digging, I think you are experiencing this issue: https://coderanger.net/2013/06/arrays-and-chef/. Chef's default mechanism for hashes is to *merge* the values, which is why you are seeing this bizarre behavior. Unfortunately I cannot think of a good way to get around this issue. I would recommend staying away from "attribute-driven" cookbooks as they will not have these problems. Sorry!

**Comment by michaellihs** [comment]
Hi @sethvargo - thanks for your work on my issue. I was already thinking of something like that, but hoped to get it work by using maps instead of arrays. Is there a good "tutorial" of how to avoid "attribute-driven" cookbooks, since I cannot think of a better way for separating my configuration from the cookbook logic...

By the way: I was looking for a "Buy me a beer"-button on your website but couldn't find one... if there is a secret way to pay you a beer via PayPal let me know :-)

**Comment by sethvargo** [comment]
Hi @michaellihs 

The best thing you can do is not use attributes. I know that sounds strange, but take a look at the jenkins cookbook itself. When I worked at Chef, our team did significant refactoring to make that cookbook as attribute-free as possible. Attributes should be used for tuning, not control flow. Instead, just call the `jenkins_plugin` resource directly in your recipe with the correct values:

```ruby
jenkins_plugin 'greenballs' do
  # ...
end
```

This is much more descriptive than a look, and it allows greater flexibility down the line if the resource were to add/remove parameters. It's also much easier to reason about than a hash.

Similarly, the resource coverage report will tell you if you forgot to test a plugin, along with the exact line in the recipe. With loop-dee-doops, that's a bit harder to decipher, since the line number will report to an inner block of a loop.
