### ISSUE TITLE
Attribute files executed when include_recipe stubbed out

### ISSUE THREAD

**Issue by andrewjamesbrown** [sethvargo/chefspec#640]
I'm using include_recipe stubs for my cookbook with code grabbed from https://gist.github.com/RoboticCheese/5505152.

In general, this works exactly as I expect, however I have noticed that attribute files in dependent cookbooks are still executed.  In some of my code, those attribute files read stuff from disk (e.g. checking values in the /proc interface), which fails during the rspec tests on OS X.

It doesn't look like this is a bug, and I can work around this by guarding these reads with an `if defined?(ChefSpec)`, but I'm wondering if there is alternative guidance?

**Comment by sethvargo** [comment]
Hi @andrewjamesbrown 

Thank you for opening an issue. Without getting too political, I would argue that making syscalls in an attributes file is an anti-pattern and that is something that should be done at the provider-level instead. I can definitely understand how it may be easier at the attribute level, but ultimately you are going to continue to encounter these types of issues, simply because of the way Chef/Ruby loads files.
