### ISSUE TITLE
No support for :before notification timer

### ISSUE THREAD

**Issue by Poohblah** [sethvargo/chefspec#679]
Chefspec only supports `:immediate`/`:immediately` and `:delayed`, but [Chef also supports a `:before` timer](https://docs.chef.io/resource_common.html#timers).

**Comment by Poohblah** [comment]
I looked into submitting a PR, but between fully adding support, writing tests, and adding examples, this would be too time-consuming for me right now, especially as a first-time Chefspec contributor.

In the meantime, I've found a workaround.  If `:before` were supported, an assertion would probably look like this:

    resource = chef_run.service('my_awesome_service')
    expect(resource).to notify('execute[my_awesome_command]').to(:run).before

This assertion can be simulated like so:

    resource = chef_run.service('my_awesome_service')
    expect(resource.before_notifications.any? do |notification|
             notification.resource.name == 'my_awesome_command' and \
             notification.action == :run
           end).to be_truthy

**Comment by chilicheech** [comment]
Running into this issue now too.

**Comment by bpholt** [comment]
FWIW, in case anyone else stumbles across this when dealing with subscriptions instead of notifications, the same logic can be used, but the resources need to be flipped from the way they're set up in the recipe.

```
service 'my_service'

file 'my_file' do
  subscribes :delete, 'service[my_service]', :before
end
```

Then, in the tests for the `file` resource:
```
chef_run.service('my_service').before_notifications.any? do |notification|
  expect(notification.resource.declared_type).to eq(:file)
  expect(notification.resource.name).to eq('my_file')
  expect(notification.action).to eq(:delete)
end
```

Using multiple expectations instead of combining them and checking for truthiness gives better error reporting, too, because rspec will report the details of exactly which expectation failed. (At least, when only one `before_notification` exists for the resource. I haven't tested this in the case where multiple exist.)

@Poohblah, thanks for posting your workaround. It was helpful for me!

**Comment by Poohblah** [comment]
@bpholt, thank you for posting that. I also had to make some changes to get subscription expectations to work correctly, but I didn't post about it to this issue report.

**Comment by sethvargo** [comment]
Fixed on master
