### ISSUE TITLE
ChefSpec with chef gem installer from cookbook's metadata. 

### ISSUE THREAD

**Issue by stuszynski** [sethvargo/chefspec#701]
Hi,

we tried to use a new "gem installation from metadata" feature but it is not working well with our ChefSpec specs. On each `chef_run` it tries to fetch data from `https://bundler.rubygems.org/api/v1/dependencies` and a couple of different sites for each gem that we place coobook's `metadata.rb` file. We are of course mocking all our scripts  for outside connections  using WebMock.

```
WebMock::NetConnectNotAllowedError:
       Real HTTP connections are disabled. Unregistered request: GET https://bundler.rubygems.org/api/v1/dependencies with headers {'Accept'=>'*/*', 'Accept-Encoding'=>'gzip;q=1.0,deflate;q=0.6,identity;q=0.3', 'Connection'=>'keep-alive', 'Keep-Alive'=>'30', 'User-Agent'=>'bundler/1.11.2 rubygems/2.4.8 ruby/2.2.4 (x86_64-apple-darwin15.4.0) '}
```
Enabling connection or stubing all the connections that bundler may produce wasn't a good idea so we manage to mitigate this issue using a monkey patch for [GemInstaller class](https://github.com/chef/chef/blob/master/lib/chef/cookbook/gem_installer.rb) (just like your extensions e.g. [here](https://github.com/sethvargo/chefspec/blob/master/lib/chefspec/extensions/chef/client.rb)) :

```
class Chef
  class Cookbook
    class GemInstaller
      attr_accessor :events
      attr_accessor :cookbook_collection

     def install
      #blank gem installation method
     end
    end
  end
end
``` 

After that, all our tests goes green but I'm not sure if it is desired approach in that case. I think we would like to test if a cookbook has a necessary gem dependencies or/and if it is installed in right version when we are doing it via `metadata.rb`. 

How would you recommend to test that? Is there a way for doing that ATM?

**Comment by sethvargo** [comment]
Hi @stuszynski 

Thank you for opening an issue. I try to keep the bug tracker reserved for issues and feature requests. I ask that you ask questions on the Chef mailing list, where more people are able to answer. Sorry to push you there, but I'm only one person, and there are many other humans on that mailing list :).

**Comment by sandervanburken** [comment]
The monkey patch from @stuszynski works well (thank you!). But what is the preferred way to handle this issue?

I have created [this](https://discourse.chef.io/t/speedup-chefspec-when-cookbook-s-have-dependencies-in-their-metadata-rb-on-gems-chef-gem/12448) topic on the Chef mailing list.

**Comment by atheiman** [comment]
this issue should be reopened, its still an issue. gem dependencies specified in a dependent cookbook's metadata.rb now require the gem to be listed in a Gemfile for the cookbook under test.

For example, [chef-sugar (cookbook) just moved its dependency on chef-sugar (gem) from a `chef_gem` resource to its metadata.rb](https://github.com/sethvargo/chef-sugar/compare/v3.6.0...v4.0.0#diff-9fd042d4cd1e8f82894bbd7dffb313ecR24). Now I have to specify `chef-sugar` in my cookbook's Gemfile because it has an indirect dependency on the chef-sugar cookbook.

I have not tried the patch from @stuszynski but it looks like it would work. This should be added to chefspec, as more cookbooks move from a `chef_gem` install of gems to the metadata.rb `gem` method, this will become more of an issue for more people.

@tas50 @lamont-granquist @coderanger thoughts? could this be reopened?

**Comment by lamont-granquist** [comment]
`chef_gem "chef-sugar"` will blow up if you don't declare it in the Gemfile either (or at least certainly once it gets required).  adding it to the Gemfile is going to be the most correct way of solving the problem, since that is the way that bundler works.

there doesn't seem to be anything really broken here to fix, it is just how bundler works, and i can't see how to usefully change anything to help.

you probably don't want to be responding to ancient closed issues either.  if you've got a proposal for the way the UX would work you should probably open it under a new issue with the proposal of the fix.  posting in an old closed issue will just get lost.
