### ISSUE TITLE
node['platform_version'] not set when using SoloRunner & fauxhai

### ISSUE THREAD

**Issue by rneu31** [sethvargo/chefspec#765]
This could be more of a user-error/question type "problem":

I am using SoloRunner and specifying a platform and version. The recipe under test uses the platform_version to determine which action to perform.

The platform version is 0.6.1 when printing out node['platform_version'] during the test.

Doing node.automatic['platform_version'] = 7.2 in the test sets the platform_version correctly, but I thought that was the purpose of using fauxhai?

Thanks in advance.

**Comment by tas50** [comment]
If you don't specify a platform Fauxhai will return a fake "chefspec" platform that lacks a lot of the details you want for mocking out data in your chef run. Instead of trying to override those values specifically just mock out the correct platform with fauxhai.  Here's an example. There's a bunch more in the examples directory:

let(:chef_run) do
    ChefSpec::ServerRunner.new(platform: 'ubuntu', version: '16.04')
                        .converge(described_recipe)
  end

For a complete list of platforms and version strings check:

https://github.com/customink/fauxhai/tree/master/lib/fauxhai/platforms

**Comment by rneu31** [comment]
I am using SoloRunner **and specifying a platform and version**

Since it seems a copy and paste of code is required:

    let(:chef_run) do
      runner = ChefSpec::SoloRunner.new(
        'platform' => 'centos',
        'version' => '7.2.1511'
      )
      runner.converge(described_recipe)
    end

**Comment by rneu31** [comment]
I'll provide a simplified example:

    describe 'cookbook::recipe' do
      context "work please" do
        let(:chef_run) do
          runner = ChefSpec::SoloRunner.new(
            'platform' => 'centos',
            'version' => '7.2.1511'
          )
          runner.converge(described_recipe)
        end
  
        it 'has the correct platform_version' do
          expect(chef_run.node['platform_version']).to eq("7.2.1511")
        end
      end 
    end


centos 7.2.1511 has 'platform_version' '7.2.1511' per https://github.com/customink/fauxhai/blob/master/lib/fauxhai/platforms/centos/7.2.1511.json
