### ISSUE TITLE
Mocking method with an object of class 

### ISSUE THREAD

**Issue by samawia-moin-confiz** [sethvargo/chefspec#785]
I have two methods without class like

```ruby
def get_load_balancer(network_client, resource_group_name, load_balancer_name)
  promise = network_client.load_balancers.get(resource_group_name, load_balancer_name)
  load_balancer = promise.value!
  return load_balancer.body
end
```

```ruby
def get_public_ip(network_client, resource_group_name, public_ip_name)
  promise = network_client.public_ip_addresses.get(resource_group_name, public_ip_name)
  public_ip = promise.value!
  return public_ip.body
end
```

I am trying to mock it like 

```ruby
@network_client = NetworkResourceProviderClient.new(token)
```

```ruby
@promise_lb = Concurrent::Promise.new
allow(@network_client).to receive(:load_balancers, :get).and_return(@promise_lb)
allow(@promise_lb).to receive(:value!).and_return(response_lb)
```

```ruby
@promise_pip = Concurrent::Promise.new
allow(@network_client).to receive(:public_ip_addresses, :get).and_return(@promise_pip)
allow(@promise_pip).to receive(:value!).and_return(response_pip)
```

Problem is, passing object in mocking isn't working. please help me with this issue. 
@sethvargo @acrmp @tas50

**Comment by sethvargo** [comment]
Hi @samawia-moin-confiz 

Thank you for opening an issue. And pinging me on Twitter. And sending me an email to my personal account. This is not a bug in ChefSpec; you are using the RSpec object model incorrectly.

This is an open source project run by volunteers who contribute in their spare time. There are a number of other users who are patiently waiting for a reply, and you are no exception.

---

As a general piece of advice from one developer to another: I understand you are facing a problem, and that problem is likely blocking your work, but 

 it looks like you're relatively new to GitHub and perhaps new to open source software. it is highly inappropriate to ping a maintainer through multiple avenues, especially after just 13 hours of opening the issue. ; that does not excuse
